<?php

namespace ByJG\AnyDataset\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-10 at 09:36:37.
 */
class ObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers ByJG\AnyDataset\Model\Object::bind
     */
    public function testBind_Constructor()
    {
        $object1 = new \Tests\Sample\SampleModel( ['Id' => 10, 'Name' => 'Joao']);
        $this->assertEquals(10, $object1->Id);
        $this->assertEquals('Joao', $object1->getName());
    }

    /**
     * @covers ByJG\AnyDataset\Model\Object::bind
     */
    public function testBind_Array()
    {
        $object1 = new \Tests\Sample\SampleModel();
        $object1->bind( ['Id' => 10, 'Name' => 'Joao'] );
        $this->assertEquals(10, $object1->Id);
        $this->assertEquals('Joao', $object1->getName());
    }

    /**
     * @covers ByJG\AnyDataset\Model\Object::bind
     */
    public function testBind_StdClass()
    {
        $stdClass = new \stdClass();
        $stdClass->Id = 10;
        $stdClass->Name = 'Joao';

        $object1 = new \Tests\Sample\SampleModel();
        $object1->bind( $stdClass );
        $this->assertEquals(10, $object1->Id);
        $this->assertEquals('Joao', $object1->getName());
    }

    /**
     * @covers ByJG\AnyDataset\Model\Object::bind
     */
    public function testBind_Iterator1()
    {
        $anydata = new \ByJG\AnyDataset\Repository\AnyDataset();
        $anydata->addField('Id', 10);
        $anydata->addField('Name', 'Joao');
        $anydata->appendRow();
        $anydata->addField('Id', 20);
        $anydata->addField('Name', 'Gilberto');

        $object1 = new \Tests\Sample\SampleModel();
        $object1->bind( $anydata->getIterator() );
        $this->assertEquals(10, $object1->Id);
        $this->assertEquals('Joao', $object1->getName());
    }

    /**
     * @covers ByJG\AnyDataset\Model\Object::bind
     */
    public function testBind_Iterator2()
    {
        $anydata = new \ByJG\AnyDataset\Repository\AnyDataset();

        $object1 = new \Tests\Sample\SampleModel();
        $object1->bind( $anydata->getIterator() );
        $this->assertEquals('', $object1->Id);
        $this->assertEquals('', $object1->getName());
    }

    /**
     * @covers ByJG\AnyDataset\Model\Object::bindTo
     */
    public function testBindTo_Object()
    {
        $object1 = new \Tests\Sample\SampleModel();
        $object1->Id = 10;
        $object1->setName('Joao');

        $object2 = new \Tests\Sample\SampleModel();
        $object1->bindTo($object2);

        $this->assertEquals(10, $object2->Id);
        $this->assertEquals('Joao', $object2->getName());
    }

    /**
     * @covers ByJG\AnyDataset\Model\Object::bindTo
     * @todo   Implement testBindTo().
     */
    public function testBindTo_stdClass()
    {
        $object1 = new \Tests\Sample\SampleModel();
        $object1->Id = 10;
        $object1->setName('Joao');

        $object2 = new \stdClass();
        $object1->bindTo($object2);

        $this->assertEquals(10, $object2->Id);
        $this->assertEquals('Joao', $object2->Name);
    }

    /**
     * @covers ByJG\AnyDataset\Model\Object::toArray
     */
    public function testToArray()
    {
        $object1 = new \Tests\Sample\SampleModel();
        $object1->Id = 10;
        $object1->setName('Joao');

        $object2 = $object1->toArray();

        $this->assertEquals(10, $object2['Id']);
        $this->assertEquals('Joao', $object2['Name']);
    }
}
