<?php

namespace ByJG\AnyDataset\Model;

use ByJG\AnyDataset\Repository\AnyDataset;
use stdClass;
use Tests\Sample\ModelGetter;
use Tests\Sample\ModelList;
use Tests\Sample\ModelList2;
use Tests\Sample\ModelList3;
use Tests\Sample\ModelPublic;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-29 at 18:59:37.
 */
class SerializerObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_ObjectGetter_1elem()
    {
        $model = new ModelGetter(10, 'Joao');

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            ['Id' => 10, 'Name' => 'Joao'],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_ObjectGetter_2elem()
    {
        $model = array(
            new ModelGetter(10, 'Joao'),
            new ModelGetter(20, 'JG')
        );

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            [
                ['Id' => 10, 'Name' => 'Joao'],
                ['Id' => 20, 'Name' => 'JG']
            ]
            , $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_ObjectPublic_1elem()
    {
        $model = new ModelPublic(10, 'Joao');

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            ['Id' => 10, 'Name' => 'Joao'],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_ObjectPublic_2elem()
    {
        $model = array(
            new ModelPublic(10, 'Joao'),
            new ModelPublic(20, 'JG')
        );

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            [
                ['Id' => 10, 'Name' => 'Joao'],
                ['Id' => 20, 'Name' => 'JG']
            ]
            , $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_StdClass_1()
    {
        $model = new stdClass();
        $model->Id = 10;
        $model->Name = 'Joao';

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            ['Id' => 10, 'Name' => 'Joao'],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_StdClass_Model()
    {
        $model = new stdClass();
        $model->Id = 10;
        $model->Name = 'Joao';
        $model->Object = new ModelGetter(20, 'JG');

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            ['Id' => 10, 'Name' => 'Joao', 'Object' => ['Id' => 20, 'Name'=>'JG']],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_Array_1()
    {
        $model = [
            'Id' => 10,
            'Name' => 'Joao'
        ];

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            ['Id' => 10, 'Name' => 'Joao'],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_Array_2()
    {
        $model = [
            'Id' => 10,
            'Name' => 'Joao',
            'Data' =>
            [
                'Code' => '2',
                'Sector' => '3'
            ]
        ];

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            [
                'Id' => 10,
                'Name' => 'Joao',
                'Data' =>
                    [
                        'Code' => '2',
                        'Sector' => '3'
                    ]
            ],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_StdClass_Array()
    {
        $model = new stdClass();
        $model->Obj = [
            'Id' => 10,
            'Name' => 'Joao'
        ];

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            [
                "Obj" => ['Id' => 10, 'Name' => 'Joao']
            ],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_Array_Scalar()
    {
        $model = new stdClass();
        $model->Obj = [
            10,
            'Joao'
        ];

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            ["Obj" => [10, 'Joao']],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_Array_Mixed()
    {
        $model = new stdClass();
        $model->Obj = [
            10,
            'Joao',
            new ModelGetter(20, 'JG')
        ];

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            ["Obj" => [10, 'Joao', ['Id'=>20, 'Name'=>'JG']]],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_Array_Array()
    {
        $model = new stdClass();
        $model->Obj = [
            'Item1' =>
            [
                10,
                'Joao'
            ],
            'Item2' =>
            [
                20,
                'JG'
            ]
        ];

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            [
                'Obj' => [
                    'Item1' =>
                        [
                            10,
                            'Joao'
                        ],
                    'Item2' =>
                        [
                            20,
                            'JG'
                        ]
                ]
            ],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_Array_Array_2()
    {
        $model = new stdClass();
        $model->Obj = [
            [
                10,
                'Joao'
            ]
        ];

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            [
                'Obj' => [
                    [
                        10,
                        'Joao'
                    ]
                ]
            ], $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_Array_Array_3()
    {
        $model = [
            [
                'Id' => 10,
                'Name' => 'Joao'
            ],
            [
                'Id' => 11,
                'Name' => 'Gilberto'
            ],
        ];

        $object = new SerializerObject($model);

        $result = $object->build();

        $this->assertEquals(
            [
                [
                    'Id' => 10,
                    'Name' => 'Joao'
                ],
                [
                    'Id' => 11,
                    'Name' => 'Gilberto'
                ],
            ],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_Array_Array_5()
    {
        $model = new stdClass;

        $model->Title = 'testing';
        $model->List = [
            [
                'Id' => 10,
                'Name' => 'Joao'
            ],
            [
                'Id' => 11,
                'Name' => 'Gilberto'
            ],
        ];
        $model->Group = "test";

        $object = new SerializerObject($model);

        $result = $object->build();

        $this->assertEquals(
            [
                'Title' => 'testing',
                'List' => [
                    [
                        'Id' => 10,
                        'Name' => 'Joao'
                    ],
                    [
                        'Id' => 11,
                        'Name' => 'Gilberto'
                    ]
                ],
                "Group" => "test"
            ],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     * @todo: Interpret Annotations
     */
    public function testCreateObjectFromModel_Collection_DontCreateNode()
    {
        $modellist = new ModelList();
        $modellist->addItem(new ModelGetter(10, 'Joao'));
        $modellist->addItem(new ModelGetter(20, 'JG'));

        $object = new SerializerObject($modellist);
        $result = $object->build();

        $this->assertEquals(
            [
                "collection" =>
                [
                    ["Id"=>10, "Name"=>"Joao"],
                    ["Id"=>20, "Name"=>"JG"]
                ]
            ],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     * @todo: Interpret Annotations
     */
    public function testCreateObjectFromModel_Collection_CreateNode()
    {
        $modellist = new ModelList2();
        $modellist->addItem(new ModelGetter(10, 'Joao'));
        $modellist->addItem(new ModelGetter(20, 'JG'));

        $object = new SerializerObject($modellist);
        $result = $object->build();

        $this->assertEquals(
            [
                "collection" =>
                    [
                        ["Id"=>10, "Name"=>"Joao"],
                        ["Id"=>20, "Name"=>"JG"]
                    ]
            ],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     * @todo: Interpret Annotations
     */
    public function testCreateObjectFromModel_Collection_SkipParentAndRenameChild()
    {
        $modellist = new ModelList3();
        $modellist->addItem(new ModelGetter(10, 'Joao'));
        $modellist->addItem(new ModelGetter(20, 'JG'));

        $object = new SerializerObject($modellist);
        $result = $object->build();

        $this->assertEquals(
            [
                "collection" =>
                    [
                        ["Id"=>10, "Name"=>"Joao"],
                        ["Id"=>20, "Name"=>"JG"]
                    ]
            ],
            $result
        );
    }

    /**
     * @covers ByJG\AnyDataset\Model\ObjectHandler::CreateObjectFromModel
     */
    public function testCreateObjectFromModel_OnlyScalarAtFirstLevel()
    {
        $model = [
            10,
            'Joao'
        ];

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            [
                10,
                'Joao'
            ],
            $result
        );
    }

    public function testEmptyValues()
    {
        $model = new stdClass();
        $model->varFalse = false;
        $model->varTrue = true;
        $model->varZero = 0;
        $model->varZeroStr = '0';
        $model->varNull = null;
        $model->varEmptyString = '';

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            [
                'varFalse' => false,
                'varTrue' => true,
                'varZero' => 0,
                'varZeroStr' => '0',
                'varNull' => null,
                'varEmptyString' => ''
            ],
            $result
        );
    }

    public function testEmptyValues_2()
    {
        $model = new ModelPublic(null, null);

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            ['Id'=>null, 'Name'=>null],
            $result
        );
    }

    public function testEmptyValues_3()
    {
        $model = new ModelGetter(null, null);

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            ['Id'=>null, 'Name'=>null],
            $result
        );
    }

    public function testEmptyValues_4()
    {
        $model = new ModelList();

        $object = new SerializerObject($model);
        $result = $object->build();

        $this->assertEquals(
            [
                'collection' => []
            ],
            $result
        );
    }

    public function testIterator()
    {
        $model = new AnyDataset();
        $model->AddField("id", 10);
        $model->AddField("name", 'Testing');

        $model->appendRow();
        $model->AddField("id", 20);
        $model->AddField("name", 'Other');

        $iterator = $model->getIterator();

        $object = new SerializerObject($iterator->toArray());
        $result = $object->build();

        $this->assertEquals(
            [
                [
                    "id" => 10,
                    "name" => "Testing"
                ],
                [
                    "id" => 20,
                    "name" => "Other"
                ]
            ],
            $result
        );
    }

    public function testFirstLevel()
    {
        $model = new stdClass();
        $model->Id = 10;
        $model->Name = 'Joao';
        $model->Object = new ModelGetter(20, 'JG');

        $object = new SerializerObject($model);
        $object->setStopFirstLevel(true);
        $result = $object->build();

        $this->assertEquals(
            ["Id" => 10, "Name" => 'Joao', 'Object' => new ModelGetter(20, 'JG')],
            $result
        );

    }

    public function testFirstLevel_2()
    {
        $model = new stdClass();
        $model->Obj = [
            10,
            'Joao',
            new ModelGetter(20, 'JG')
        ];

        $object = new SerializerObject($model);
        $object->setStopFirstLevel(true);
        $result = $object->build();

        $this->assertEquals(
            ["Obj" => [10, 'Joao', new ModelGetter(20, 'JG')]],
            $result
        );
    }

}
